### ISSUE TITLE
OpenSSL error when I try to do anything

### ISSUE THREAD

**Issue by thoraxe** [varyonic/paypal-subscriptions-sdk-ruby#3]
I am suddenly getting weird OpenSSL errors that I can't troubleshoot, trace, or debug any further because the error is very... empty.

```
PayPal::SDK::Subscriptions::Plan.find("I-539WTJ0XHUL2")
Request[post]: https://api.sandbox.paypal.com/v1/oauth2/token
Request.body=grant_type=client_credentials	request.header={"User-Agent"=>"PayPalSDK/PayPal-Subscriptions-Ruby-SDK 0.3.1 (paypal-sdk-core 1.7.4; ruby 2.6.6p146-x86_64-linux;OpenSSL 1.1.1d  10 Sep 2019)", "Content-Type"=>"application/x-www-form-urlencoded", "Authorization"=>"Basic xxx"}
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
from /usr/local/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock'
```

It's not even clear WHERE the error is coming from.

Any ideas? I tried updating my operating system, and net::HTTP will open api.sandbox just fine. I'm hoping this is somehow not connected to the deprecation of the base sdk gem.

**Comment by thoraxe** [comment]
It appears that the upstream paypal-sdk gem was bundling its own certificates:
https://github.com/paypal/PayPal-Ruby-SDK/tree/master/data

We would need to either update these in order to make this error go away. I guess we might have to hard fork the V1 SDK sooner rather than later, or at least come up with our own subset.

**Comment by varyonic** [comment]
Per our conversation the short term workaround is

    gem 'paypal-sdk-rest', git: 'https://github.com/varyonic/PayPal-Ruby-SDK/'

Will update when this changes.

**Comment by varyonic** [comment]
I have [forked the REST SDK](https://rubygems.org/gems/paypal-sdk-rest-pmrb) as `paypal-sdk-rest-pmrb`, adding the SSL fix.
